busybox: init-ifupdown: create /run/network if not existing

diff --git a/meta/recipes-core/init-ifupdown/init-ifupdown-1.0/init b/meta/recipes-core/init-ifupdown/init-ifupdown-1.0/init
--- a/meta/recipes-core/init-ifupdown/init-ifupdown-1.0/init
+++ b/meta/recipes-core/init-ifupdown/init-ifupdown-1.0/init
@@ -14,6 +14,13 @@ PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
 
 [ -x /sbin/ifup ] || exit 0
 
+if [ ! -d /run/network ]; then
+    if ! mkdir -p /run/network; then
+	echo "failed to create /run/network" >&2
+	exit 1
+    fi
+fi
+
 check_network_file_systems() {
     [ -e /proc/mounts ] || return 0
 
